import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Aside from "@/components/header/aside/aside";
import { OnboardingProvider } from "@/lib/context";
import MainWrapper from "@/components/mainWrapper/mainWrapper";

const josefinSans = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        <OnboardingProvider>
          <Header />
          <Aside />
          <MainWrapper>{children}</MainWrapper>
        </OnboardingProvider>
      </body>
    </html>
  );
}
